---
- name: Network Configuration
  hosts: router
  gather_facts: false  # Consider enabling for initial configuration
  vars:
    ansible_user: cnit381
    ansible_password: cnit381pass
    ansible_become: yes
    ansible_become_password: cnit381pass
    ansible_connection: network_cli  # Explicitly define the connection type

  tasks:
    - name: Change hostname
      cisco.ios.ios_config:
        lines:
          - hostname {{ inventory_hostname }}  # Use inventory_hostname variable

    - name: Change domain name
      cisco.ios.ios_system:
        domain_name: cnit381.com

    - name: Enable SSH
      cisco.ios.ios_config:
        lines:
          - ip ssh version 2