---
- name: Create VLANS
  hosts: switches
  gather_facts: no
  connection: network_cli
  become_method: enable

  tasks:
    - name: Create VLANs 10-30
      cisco.ios.ios_vlans:
        config:
        - name: Management
          vlan_id: 10
        - name: Sales
          vlan_id: 20
        - name: Marketing
          vlan_id: 30
